name: fileflow
description: "P2P File Transfer App"
publish_to: 'none' 
version: 1.1.0

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  flutter_riverpod: 
  network_info_plus: 
  device_info_plus:
  permission_handler: 
  path_provider: 
  file_picker: 
  qr_flutter:
  mobile_scanner: 
  intl: 
  hive_flutter: 
  shelf: 
  shelf_router: 
  mime: 
  desktop_drop: 
  pointycastle: 
  receive_sharing_intent: 
  pem: 
  google_fonts: 
  url_launcher: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true