name: fileflow
description: "P2P File Transfer App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  network_info_plus: ^7.0.0
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mime: ^2.0.0
  desktop_drop: ^0.7.0
  pointycastle: ^4.0.0
  receive_sharing_intent: ^1.8.1
  pem: ^2.0.6
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true